kind: PersistentVolume
apiVersion: v1
metadata:
  name: telegram-support-bot
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/telegram-support-bot"